sudo: false  # run travis jobs in containers
language: python
cache:
  directories:
    - $PWD/wheelhouse  # cache wheels so that we don't hit network everytime
env:
  global:
    - PIP_FIND_LINKS=$PWD/wheelhouse
  matrix:
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=pypy3
install:
  - pip wheel tox  # no wheel distribution for tox on pypi yet   
  - pip install tox 
script: tox
